
name: "GoStacker"
mode: "dev"
port: 8081
start_time: "2024-06-10 12:00:00"
machine_id: 1
push_mod: "standalone" # "standalone" or "gateway"
address: "127.0.0.1:8081"

log:
  level: "debug"
  filename: "GoStacker.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "GoStacker"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 50
  batch_size: 128

group_cache:
  enabled: true
  cache_ttl_seconds: 86400        # 24 hours
  dirty_retention_seconds: 604800 # 7 days
  flush_interval_seconds: 5       # flusher tick interval
  batch_size: 100
  max_retries: 3

jwt:
  secret: "your_jwt_secret_key"
  expire_duration: 7200 # in seconds

ws:
  max_write_wait: 10 # in seconds
  max_read_wait: 60  # in seconds

dispatcher:
 send_channel_size: 1024